version: "3.8"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: thoaiky1992
      MYSQL_USER: thoaiky1992
      MYSQL_PASSWORD: thoaiky1992
      MYSQL_ROOT_PASSWORD: thoaiky1992
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - shop-network
#Networks
networks:
  shop-network:
    driver: bridge
#Volumes
#volumes:
#  dbdata:
#    name: dbdata
#    driver: local
